---
driver:
  name: docker
  privileged: true
  use_sudo: false

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  roles_path: catalog/
  requirements_path: requirements.yml
  hosts: all
  playbook: tests/test.yml
  ansible_vault_password_file: ansible-secret.txt
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_verbose: true
  ansible_diff: true
  ansible_verbosity: 2
  idempotency_test: true
  #ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  #ansible_version:
  #custom_pre_install_command:	nil	Custom shell command to be used at beginning of install stage. Can be multiline.
  #custom_pre_play_command:	nil	Custom shell command to be used before the ansible play stage. Can be multiline. See examples below.
  #custom_post_install_command:	nil	Custom shell command to be used at after the install stage. Can be multiline.
  #custom_post_play_command:	nil	Custom shell command to be used after the ansible play stage. Can be multiline. See examples below.
  #env_vars:	Hash.new	Hash to set environment variable to use with ansible-playbook command
  #extra_vars: git c
  #extra_vars_file:	nil	file containing environment variables e.g. private_vars/production.yml site.yml Don't prefix with a @ sign.
  #group_vars_path:	group_vars	Ansible repo group_vars directory
  #host_vars_path:	host_vars	Ansible repo hosts directory
  #command: |

platforms:
 # Ubuntu Trusty with Upstart
  - name: ckan23-dk
    driver_config:
      image: rndmh3ro/docker-ubuntu1404-ansible:latest
      platform: ubuntu
  - name: ckan23-vb
    driver:
      name: vagrant
      box: ubuntu/trusty64
      box_check_update: true
  # Ubuntu Xenial with Systemd
  - name: ckan28-gsa-dk
    driver_config:
     image: rndmh3ro/docker-ubuntu1604-ansible:latest
     platform: ubuntu
  - name: ckan28-mas-dk
    driver_config:
     image: rndmh3ro/docker-ubuntu1604-ansible:latest
     platform: ubuntu
  - name: ckan28-gsa-vb
    driver:
      name: vagrant
      #pre_create_command: cp .vagrant_plugins.json {{vagrant_root}}/ && vagrant plugin bundle
      use_vagrant_hostmanager_plugin: true
      box: ubuntu/xenial64
      box_check_update: true
      provision: hostmanager
      vm_hostname: catalog-gsa.local
      #gui: false
      customize:
        memory: 4096
      network:
        - ["private_network", {ip: 192.168.10.82}]
  - name: ckan28-mas-vb
    driver:
      name: vagrant
      #pre_create_command: cp .vagrant_plugins.json {{vagrant_root}}/ && vagrant plugin bundle
      use_vagrant_hostmanager_plugin: true
      box: ubuntu/xenial64
      box_check_update: true
      vm_hostname: catalog-mas.local
      #gui: false
      customize:
        memory: 4096
      network:
        - ["private_network", {ip: 192.168.10.81}]

suites:
  - name: dev
  - name: test
  - name: stage
  - name: prod

